openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        '200':
          description: ''
  /trends/zenn:
    get:
      operationId: TrendsController_getZennTrends
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ZennTrendsResponse'
  /trends/qiita:
    get:
      operationId: TrendsController_getQiitaTrends
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QiitaTrendsResponse'
info:
  title: trend-tech-api
  description: trend-tech-api API仕様書
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas:
    ZennTrendsResponse:
      type: object
      properties: {}
    QiitaTrendsResponse:
      type: object
      properties: {}
