name: CI

on:
  pull_request:
    branches:
      - master
      - develop

env:
  NODE_VERSION: 18.x

jobs:
  lint_and_generate_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install yarn dependencies
        run: yarn install
      - name: Run Prettier
        run: yarn format
      - name: Run ESLint
        run: yarn lint
      - name: Generate OpenAPI docs
        run: yarn openapi:export
      - name: Generate ReDoc html
        run: yarn redocly
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'CI: format, lint, generate docs'
  build:
    runs-on: ubuntu-latest
    needs: lint_and_generate_docs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install yarn dependencies
        run: yarn install
      - name: Build
        run: yarn build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install yarn dependencies
        run: yarn install
      - name: Run tests
        run: yarn test:cov
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: jest-report
          path: ./jest-html-reporters.html
          retention-days: 7
