name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [labeled]

jobs:
  review:
    if: ${{ contains(github.event.*.labels.*.name, 'gpt review') }}
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Japanese
